import type { CheckpointResult, RunPlan, GelResult } from '../models/types';
import { formatTime, formatPace } from '../algorithm/PacePlanner';

interface Props {
  plan: RunPlan;
  results: CheckpointResult[];
  gelResults?: GelResult[];
  profileMode?: 'table' | 'chart';
  getChartSvgHtml?: () => string | null;
}

function bufferStr(min: number | null): string {
  if (min === null) return '—';
  return `${min >= 0 ? '+' : ''}${Math.round(min)}min`;
}

function generateTableHtml(plan: RunPlan, results: CheckpointResult[], gelResults: GelResult[]): string {
  const goalH = Math.floor(plan.goalTimeSec / 3600);
  const goalMin = Math.floor((plan.goalTimeSec % 3600) / 60);
  const date = new Date().toLocaleDateString();
  const hasCutoff = results.some(r => r.cutoffTime);

  type Row = { kind: 'cp'; data: CheckpointResult } | { kind: 'gel'; data: GelResult };
  const allRows: Row[] = [
    ...results.map(r => ({ kind: 'cp' as const, data: r })),
    ...gelResults.map(g => ({ kind: 'gel' as const, data: g })),
  ].sort((a, b) => a.data.distM - b.data.distM);

  let cpIdx = 0;
  const rows = allRows.map(row => {
    if (row.kind === 'gel') {
      const g = row.data;
      return `<tr class="gel">
        <td>·</td>
        <td class="name" style="color:#e67e00">Gel ${g.gelNumber}</td>
        <td>${(g.distM / 1000).toFixed(1)}</td>
        <td>—</td>
        <td class="bold">${formatTime(g.etaMs)}</td>
        <td>—</td>
        <td class="bold">${formatTime(g.etaMs)}</td>
        ${hasCutoff ? '<td>—</td><td>—</td>' : ''}
      </tr>`;
    }
    const r = row.data;
    cpIdx++;
    return `<tr>
      <td>${cpIdx}</td>
      <td class="name">${r.name}${r.note ? `<div class="note">${r.note}</div>` : ''}</td>
      <td>${(r.distM / 1000).toFixed(1)}</td>
      <td>${formatPace(r.segmentPaceSecPerKm)}</td>
      <td class="bold">${formatTime(r.etaMs)}</td>
      <td>${r.type === 'aid' ? `${r.plannedStopMin}min` : '—'}</td>
      <td class="bold">${formatTime(r.leaveAtMs)}</td>
      ${hasCutoff ? `<td>${r.cutoffTime ?? '—'}</td>` : ''}
      ${hasCutoff ? `<td class="${r.cutoffBufferMin !== null && r.cutoffBufferMin < 10 ? 'red' : ''}">${bufferStr(r.cutoffBufferMin)}</td>` : ''}
    </tr>`;
  }).join('');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <title>TopoPace — ${plan.name}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Arial, sans-serif; font-size: 9pt; color: #000; padding: 12mm; }
    h1 { font-size: 12pt; margin-bottom: 2mm; }
    .meta { font-size: 8pt; color: #555; margin-bottom: 5mm; }
    table { width: 100%; border-collapse: collapse; }
    th { font-size: 7.5pt; text-transform: uppercase; letter-spacing: .04em; padding: 2px 5px; border-bottom: 1.5px solid #000; text-align: center; white-space: nowrap; }
    td { padding: 2.5px 5px; border-bottom: .5px solid #ccc; text-align: center; vertical-align: top; }
    td.name { text-align: left; font-weight: 600; }
    .note { font-size: 7.5pt; font-weight: 400; color: #555; margin-top: 1px; }
    .bold { font-weight: 700; }
    .red { color: #c00; font-weight: 700; }
    tr.gel td { color: #e67e00; border-bottom-style: dashed; }
    footer { margin-top: 5mm; font-size: 7.5pt; color: #777; }
    @media print { @page { margin: 10mm; } }
  </style>
</head>
<body>
  <h1>TopoPace — ${plan.name}</h1>
  <div class="meta">Start: ${plan.raceStartTime} &nbsp;·&nbsp; Goal: ${goalH}h ${goalMin}min &nbsp;·&nbsp; Generated: ${date}</div>
  <table>
    <thead>
      <tr>
        <th>#</th><th style="text-align:left">Checkpoint</th><th>km</th>
        <th>Pace</th><th>ETA</th><th>Stop</th><th>Leave</th>${hasCutoff ? '<th>Cutoff</th><th>Buffer</th>' : ''}
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>
  <footer>TopoPace race planner · topopace.app</footer>
</body>
</html>`;
}

// Profile mode: the SVG already contains the schedule strip (generated by ElevationChart).
// We just embed the serialised SVG and let it fill the page width.
function generateProfileHtml(plan: RunPlan, svgHtml: string): string {
  const goalH = Math.floor(plan.goalTimeSec / 3600);
  const goalMin = Math.floor((plan.goalTimeSec % 3600) / 60);
  const date = new Date().toLocaleDateString();

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <title>TopoPace — ${plan.name}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Arial, sans-serif; font-size: 9pt; color: #000; padding: 10mm; }
    h1 { font-size: 13pt; margin-bottom: 2mm; }
    .meta { font-size: 8pt; color: #555; margin-bottom: 5mm; }
    .chart-wrap { width: 100%; line-height: 0; }
    .chart-wrap svg { width: 100%; height: auto; display: block; }
    footer { margin-top: 6mm; font-size: 7.5pt; color: #888; }
    @media print {
      @page { size: A4 portrait; margin: 10mm; }
      body { padding: 0; }
      .chart-wrap svg { width: 100%; height: auto; }
    }
  </style>
</head>
<body>
  <h1>TopoPace — ${plan.name}</h1>
  <div class="meta">Start: ${plan.raceStartTime} &nbsp;·&nbsp; Goal: ${goalH}h ${goalMin}min &nbsp;·&nbsp; Generated: ${date}</div>
  <div class="chart-wrap">${svgHtml}</div>
  <footer>TopoPace race planner · topopace.app</footer>
</body>
</html>`;
}

export default function PrintPlan({ plan, results, gelResults = [], profileMode, getChartSvgHtml }: Props) {
  function handlePrint() {
    const win = window.open('', '_blank');
    if (!win) return;

    let html: string;
    if (profileMode === 'chart' && getChartSvgHtml) {
      const svgHtml = getChartSvgHtml();
      html = svgHtml
        ? generateProfileHtml(plan, svgHtml)
        : generateTableHtml(plan, results, gelResults);
    } else {
      html = generateTableHtml(plan, results, gelResults);
    }

    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => win.print(), 300);
  }

  return (
    <button className="primary" style={{ padding: '10px 24px', width: '100%' }} onClick={handlePrint}>
      🖨 Print / Save as PDF
    </button>
  );
}
